### ISSUE TITLE
vuls report can't send mail to smtp.office365.com

### ISSUE THREAD

**Issue by jirib** [future-architect/vuls#1022]
# What did you do?

Trying  to get Vuls report via mail to a domain hosted behind smtp.office365.com. It seems Vuls has 'PLAIN' auth hardcoded https://github.com/future-architect/vuls/blob/b37df89fb141351b524209a11b523cfee063297e/report/email.go#L181 ?

# What did you expect to happen?

Email reporting should work.

# What happened instead?

```
[Jul 15 15:17:36] ERROR [localhost] Failed to report. err: Failed to send emails:
    github.com/future-architect/vuls/report.(*emailSender).Send
        /go/src/github.com/future-architect/vuls/report/email.go:192
  - 504 5.7.4 Unrecognized authentication type [PR2P264CA0021.FRAP264.PROD.OUTLOOK.COM]
```

# Steps to reproduce the behaviour

* define 'email' section in `config.toml` and use an account hosted behind smtp.office365.com

# Configuration

```
[email]
smtpaddr = "smtp.office365.com"
smtpport = "587"
from = "foo@example.com"
to = ["foo@example.com"]
user = "<valid auth user>"
password = "<valid auth password>"
subjectprefix = "[vuls]"
```

* Vuls environment:

```
vuls v0.10.0 build-20200703_050746_11a7a0c
```

**Comment by DaikiYamakawa** [comment]
@jirib Hello, I'm @DaikiYamakawa and I have assigned me to this issue. Thank you for your report. 

# Why did we have this problem?
net/smtp library (https://golang.org/pkg/net/smtp/) only have CRAMMD5Auth/PlainAuth and smtp.office365.com does not support SimpleAuth.

## Result of EHLO command
- smtp.office365.com
![smtp office365 com](https://user-images.githubusercontent.com/39241071/89982254-55334680-dcb0-11ea-91ad-412dc794910d.png)

# How do we solve this problem?
We will support PlainAuth/LoginAuth when sending reports via email because smtp.office365.com support LoginAuth. 

I will use two another library.
- https://github.com/emersion/go-smtp
- https://github.com/emersion/go-sasl

If you know of a mail server that can't send email with these two authentication methods(Plain/Login) and is used by many people, please let me know.
Thank you.

**Comment by DaikiYamakawa** [comment]
@jirib Hello, I've implemented it so that I can support LOGIN authentication as well, so I was able to resolve this issue. See the pull request for details. Thank you.
