### ISSUE TITLE
Vuls having trouble to detect kernel version

### ISSUE THREAD

**Issue by ImplicitDeny** [future-architect/vuls#1214]
Hi there,

I'm experimenting with vuls on some demo servers of my company. I encounter some problems when trying to view results with `vuls tui` on my test machine : `WARN [localhost] The OVAL name of the running kernel image {Release:5.4.0-71-generic Version: RebootRequired:false} is not found. So vulns of 'linux' wll be detected. server: *********`

As you can see, it seems that the retrieved kernel string is containing some flags that `vuls tui`can't deal with. The target test machine is a simple webserver on which I'm able to run as root (however this is simply a fast scan result), recently installed and quite up to date under Ubuntu 20.04.2 LTS (5.4.0-71-generic). So it seems that the gathering process did correctly recovered the kernel version, but what about these flags ? Is my server misconfigured (it should be straight out-of-the-box vanilla Ubuntu with no exotic setting and almost nothing installed on it) ? Am I missing a config file for `vuls tui` somewhere ?

As of now, it is strictly unusable, as there is something like 930+ potential CVE detected on this server. Manually (or scriptically) browsing through this list isn't that much fun, I'd rather let it all to `vuls tui` if possible.

**Comment by ImplicitDeny** [comment]
I browsed through the code in order to try to find what is wrong and why, and so far I spotted that this warning message is generated here : https://github.com/future-architect/vuls/blob/740781af56a5e7e957e8d95e1f8e9bd850eb8f50/oval/debian.go#L377

This is due to this `if` block failing : `if v, ok := r.Packages[linuxImage]; ok {`. I'm a total noob in Go but I understand that there is no key corresponding to the value of `linuxImage` in `r.Packages`. `linuxImage` is composed, in my case, of a static string "linux-image-" and the release value of the running kernel extracted for the results. The end result is `linux-image-5.4.0-71-generic`.

I'm trying to swim up the code, searching for how is crafter this `r.Packages` thing, but so far no luck =/

**Comment by PhilPhonic** [comment]
Same problem here.
```
time="Jul 28 12:32:49" level=warning msg="The OVAL name of the running kernel image {Release:5.4.0-77-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: <hostname>"
```

OS is Ubuntu 20.04

**Comment by Kulgar** [comment]
Same here, same OS

**Comment by MaineK00n** [comment]
@ImplicitDeny 

This message is displayed when `kernelPkgInOVAL` is `""`.
https://github.com/future-architect/vuls/blob/2923cbc645fbc7a37d50398eb2ab8febda8c3264/oval/debian.go#L454-L459

`kernelPkgInOVAL` is possibly to be changed here.
https://github.com/future-architect/vuls/blob/2923cbc645fbc7a37d50398eb2ab8febda8c3264/oval/debian.go#L420-L425

The `kernelNamesInOval` used for is a list of kernel-related packages that appear in the OVAL of the Ubuntu version to be scanned.
For example, the kernel-related package names that appear in OVAL for Ubuntu 20.04 are as follows.
https://github.com/future-architect/vuls/blob/2923cbc645fbc7a37d50398eb2ab8febda8c3264/oval/debian.go#L331-L358

When I look for packages named linux in a certain Ubuntu 20.04 environment, there are no packages defined in `kernelNamesInOval`. (This is probably the same situation as the questioner.)
```console
vagrant@ubuntu2004:~$ dpkg -l | awk '{print $2}' | grep ^linux
linux-base
linux-cloud-tools-5.4.0-42
linux-cloud-tools-5.4.0-42-generic
linux-cloud-tools-5.4.0-97
linux-cloud-tools-5.4.0-97-generic
linux-cloud-tools-common
linux-cloud-tools-generic
linux-cloud-tools-virtual
linux-firmware
linux-generic
linux-headers-5.4.0-42
linux-headers-5.4.0-42-generic
linux-headers-5.4.0-97
linux-headers-5.4.0-97-generic
linux-headers-generic
linux-image-5.4.0-42-generic
linux-image-5.4.0-97-generic
linux-image-generic
linux-libc-dev:amd64
linux-modules-5.4.0-42-generic
linux-modules-5.4.0-97-generic
linux-modules-extra-5.4.0-42-generic
linux-modules-extra-5.4.0-97-generic
linux-tools-5.4.0-42
linux-tools-5.4.0-42-generic
linux-tools-common
```

If reporting in this environment (same for tui), the following warn log will be displayed because `kernelPkgInOVAL` is `""`.
```console
$ vuls report
...
[Feb  6 23:37:23]  WARN [vagrant] The OVAL name of the running kernel image {Release:5.4.0-97-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: vagrant
...
```

However, as shown in the log, if `kernelPkgInOVAL` is `""` (i.e., the package defined in `kernelNamesInOval` is not found), kernelPkgInOVAL is treated as linux and vulnerabilities related to linux are checked from OVAL. Check for linux-related vulnerabilities from OVAL.
https://github.com/future-architect/vuls/blob/2923cbc645fbc7a37d50398eb2ab8febda8c3264/oval/debian.go#L454-L459

Therefore, the conclusion is that the package for your kernel is not defined in OVAL, so you can temporarily add it as a linux package and search OVAL, not that there is anything wrong with your environment.

**Comment by MaineK00n** [comment]
Sorry, I've been talking about implementation for a long time, and it's not easy to understand.
Yes, you are right, there is no need for you to do anything. It's working fine.
