### ISSUE TITLE
Normalize character set

### ISSUE THREAD

**Issue by sheo0147** [future-architect/vuls#279]
General Issue.

Vuls imports some text data from Database such as NVD/JVN... and so on.
But Vuls code is not normalize charset before parse or store to DB and so on.

* Normalize character set from any to Unicode when importing some text data.
* Normalize character set to Unicode ( or selectable, but default is unicode) when outputs like Mail, Slack and so on.

**Comment by hogehogehugahuga** [comment]
I think the default character code is UTF-8.

- https://golang.org/ref/spec#Source_code_representation

As for input, I seems deal with below.

- go-cve-dictionary: Set the output of the program to UTF8.
- or Convert go-cve-dictionary output Charactor-code to UTF-8 with vuls

As for output, When the data of go-cve-dictionary use UTF-8 or convert to UTF-8

- -report-mail needs `Content-Type: text/plain; charset=utf8`

Mail header require charset, because Sometimes the mail software can not identify the character code.
Other report option seems to UTF-8.

I think, if the input charactor code is unified in UTF-8, output character code will be the default UTF-8.

**Comment by hogehogehugahuga** [comment]
I send pull request #280. It fix Content-Type header issue.
The rest, output UTF-8 charset from go-cve-dictionary when Other multi byte country data.
