### ISSUE TITLE
Provide a command line flag that will automatically install aptitude on debian?

### ISSUE THREAD

**Issue by PaulFurtado** [future-architect/vuls#390]
There are many debian docker containers in the wild that don't have aptitude installed and vuls requires aptitude to get changelogs for them. Though it feels dirty to do in vuls, it would be really convenient if vuls provided a command line flag or config option that would automatically install aptitude if necessary, so that people who really want to scan their infrastructure don't need to rebuild their docker containers to do so.

What do you think? I'm willing to work on a PR for this, but I wanted to see how you felt about it first.

**Comment by kotakanbe** [comment]
A while ago, there was a subcommand to install dependency packages.
https://github.com/future-architect/vuls/pull/375

The prepare command has been deleted because dependent packages can be easily installed manually or by Ansible etc and to minimize the root privilege defined in /etc/sudoers.

I think Vuls doesn't need the option.
