### ISSUE TITLE
Best effort instead of giving up

### ISSUE THREAD

**Issue by theonlydoo** [future-architect/vuls#51]
When some connexion are failing the following error occurs before the slack report and Vuls gives up :

```
time="May 10 13:47:09" level=error msg="Timeout occured while detecting" 
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "a"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "b"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "c"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "d"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "e"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "f"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "g"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "h"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "i"
time="May 10 13:47:09" level=error msg="Failed to detect. servername: "j"
time="May 10 13:47:09" level=error msg="Failed to init servers. Check the configuration. err: Failed to detect the type of OS. err: Timeout" 
```
n.b. this is related to https://github.com/future-architect/vuls/issues/37 since those errors are coming from the fact that available ciphers are not matching.

**Comment by kotakanbe** [comment]
That error was occurred when Vuls attempt to detect the type of OS of each server defined in a config file. In the above case, Vuls was unable to ssh to the servers because of the reason #37 as you have written above .

I think it's important to notify as fast as possible if the config is something wrong.
So, If the config is wrong Vuls gives up to scan with printing the error message.
