### ISSUE TITLE
limit the number of parallel scans ?

### ISSUE THREAD

**Issue by aderumier** [future-architect/vuls#871]
Hi,

is it possible to limit the number of parallel scans ?

I have currently 3000 servers in config.toml, and I'm getting max open file limit on vuls server,
and I would like also to limit the load on targets at the same time.

**Comment by kotakanbe** [comment]
Will this link help you?

https://github.com/basho/basho_docs/blob/master/content/riak/kv/2.0.6/using/performance/open-files-limit.md#changing-the-limit

**Comment by aderumier** [comment]
hi, yes I could setup more open files limits. but having 3000 vms doing a fast-root scan at the same time (apt-update, apt changelog,...),  can dp a huge load too.

**Comment by kotakanbe** [comment]
`apt-chagelog` is not used anymore in the latest version of vuls.
I recommend update vuls to the latest version.

`fast scan mode` is more lightweight than `fast-root scan mode` because `fast scan mode` does not issue metadata update commands such as `apt-get update` or `repoquery`. But `fast scan mode` can not show the candidate version of the upgradable pacakges.

**Comment by aderumier** [comment]
> `apt-chagelog` is not used anymore in the latest version of vuls.
> I recommend update vuls to the latest version.
> 
thanks, I didn't know about this

seem that it's still in documentation graphs

https://github.com/vulsdoc/vuls/blob/master/website/static/graphml/vuls-scan-flow-fast-root.graphml
https://github.com/vulsdoc/vuls/blob/master/website/static/graphml/vuls-scan-flow-deep.graphml

**Comment by kotakanbe** [comment]
fixed
https://vuls.io/docs/en/architecture-fast-root-scan.html
