### ISSUE TITLE
vuls report giving incorrect package version and give cve related to it.

### ISSUE THREAD

**Issue by thinksabin** [future-architect/vuls#873]
# What did you do? (required. The issue will be **closed** when not provided.)
vuls scan machinename

# What did you expect to happen?
detection of correct mysql-common package installed in the machine.

# What happened instead?
**detected incorrect version of mysql-common package.**
vuls detected **mysql-common** 5.7.13-0ubuntu0.16.04.2 installed in the machine where as in the machine mysql-common is 5.7.25-0ubuntu0.16.04.2. Since it detected 5.7.13 the cve CVE-2018-3200 was reported in the report which is false positive. 

manual package version check in ubuntu 16.04.
dpkg -l | grep mysql-
ii  mysql-common                               5.7.25-0ubuntu0.16.04.2                    all          MySQL database common files, e.g. /etc/mysql/my.cnf

To check the commit hash of HEAD
$ vuls -v

vuls v0.7.0 build-20190615_143533_8c3b305

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by kotakanbe** [comment]
First, Update vuls to the latest version.
Due to maintenance costs, I only support the latest version.

Please paste the output of this command.
`dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${Source},\${source:Version}\n"`
https://github.com/future-architect/vuls/blob/master/scan/debian.go#L349

and

` cat results/current/c610.json | jq "." | grep -C 10 mysql`

**Comment by kotakanbe** [comment]
If you are still having trouble, please reopen this issue.
