### ISSUE TITLE
BUG: -o pipefail is not work on FreeBSD's /bin/sh. because it isn't bash

### ISSUE THREAD

**Issue by sheo0147** [future-architect/vuls#91]
Vuls supports FreeBSD just now.
It is awesome. Very very thanks to the work!

I found 1 problem.

see following line.
`DEBU[0000] SSH executed. cmd: set -o pipefail; uname, status: <nil>`

This line is one of the debug log.

I think vuls assumes that target hosts shell is bash, but FreeBSD's shell is not bash.

So, on FreeBSD, you cannot use `-o pipefail` option.

**Comment by kotakanbe** [comment]
- Run with csh
Fixed in https://github.com/future-architect/vuls/pull/98 
Now vuls execute commands without -o pipefail option on FreeBSD.
You don't need to create a user with bash login shell.

- non-root privilege
There is no need to use root privilege user on FreeBSD servers.
Vuls can scan using non-root users on FreeBSD.

(root privilege is needed on Amazon, CentOS, RHEL, Ubuntu and Debian for now)
