### ISSUE TITLE
coreOS is not in Supported OS

### ISSUE THREAD

**Issue by thomas10-10** [future-architect/vuls#933]
Hello
coreOS is not in Supported OS,
Is there an alternative way to scan for vunerabilities on coreOS ?

Thanks

**Comment by gy741** [comment]
Hello, @thomas10-10 

I think, CoreOS is designed to be bare-bones and thus contain just enough functionality to provide a clustering infrastructure, and nothing more. There's no package manager since there shouldn't be a need to install anything; Applications and/or services run in containers.

Do you have a package installed in CoreOS?

**Comment by thomas10-10** [comment]
Hello,@gy741 

Yes, there's no package manager installed in my CoreOS, but I was thinking of scanning the programs, libraries installed by default in the bin folders like openssl.

In any case CoreOS Container Linux will reach its end of life, so I'm going to close this enhancement.

Thanks !
